name: country_phone_validator
description: A package to validate phone numbers based on country codes.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.4
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
